## Install Dependencies

In [ ]:
!pip install tensorflow==2.4.1 tensorflow-gpu==2.4.1 opencv-python matplotlib

In [1]:
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
import cv2

## Load model and allocate tensors

In [2]:
interpreter = tf.lite.Interpreter(model_path='lite-model_movenet_singlepose_lightning_3.tflite')
interpreter.allocate_tensors()

## Make Detections

In [26]:
cap = cv2.VideoCapture(0)
while cap.isOpened():
    _,frame=cap.read()
    
    #Reshape Image
    img = frame.copy()
    img = tf.image.resize_with_pad(np.expand_dims(img,axis=0),192,192)
    input_image = tf.cast(img,dtype=tf.float32)
    
    #setup input and output
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    
    #Make predictions
    interpreter.set_tensor(input_details[0]['index'],np.array(input_image))
    interpreter.invoke()
    keypoints_with_scores = interpreter.get_tensor(output_details[0]['index'])
    print(keypoints_with_scores)
    
    #Rendering
    draw_connections(frame,keypoints_with_scores,EDGES,0.4)
    draw_keypoints(frame,keypoints_with_scores,0.4)
    cv2.imshow('MoveNet Lightning',cv2.flip(frame,1))
    if cv2.waitKey(10) & 0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

[[[[0.74418944 0.4861698  0.54875106]
   [0.66618884 0.56270146 0.48591852]
   [0.6912521  0.44944426 0.7721274 ]
   [0.7059805  0.6793715  0.54990506]
   [0.72002023 0.4366783  0.52707934]
   [0.86976933 0.7079632  0.26573265]
   [0.8648857  0.33752394 0.42144695]
   [0.85485184 0.7328571  0.00745615]
   [0.93841827 0.286892   0.01006603]
   [0.70205843 0.70736355 0.03699416]
   [0.8527514  0.4128875  0.02309865]
   [0.51933545 0.67121005 0.04062864]
   [0.63016784 0.3739407  0.0150921 ]
   [1.0216383  0.63266337 0.0028773 ]
   [0.8616153  0.27789947 0.00678492]
   [0.99866045 0.02623299 0.01031595]
   [0.26466215 0.41198057 0.03157452]]]]
[[[[ 0.74830806  0.48837802  0.5434013 ]
   [ 0.6698894   0.56009626  0.52108485]
   [ 0.69534326  0.4502091   0.7025486 ]
   [ 0.6984538   0.67471904  0.6598781 ]
   [ 0.7205833   0.43571264  0.5366891 ]
   [ 0.87766165  0.7248339   0.21687958]
   [ 0.85453886  0.33782464  0.43299538]
   [ 0.8486337   0.7515268   0.01055083]
   [ 0.9360096   0.2810

[[[[0.76651454 0.59513795 0.6301675 ]
   [0.69244426 0.653993   0.59933144]
   [0.7023286  0.5235845  0.3433794 ]
   [0.7210972  0.70750797 0.5537923 ]
   [0.7361531  0.44972655 0.65710604]
   [0.8900668  0.74753654 0.21005306]
   [0.84791803 0.3442834  0.44404158]
   [0.8487911  0.8399316  0.0077039 ]
   [0.9321791  0.3137076  0.01005027]
   [0.76370305 0.72546625 0.01177004]
   [0.862638   0.41374582 0.01171723]
   [0.53522193 0.6597717  0.03044602]
   [0.6005037  0.39020014 0.04179597]
   [0.7242765  0.9660977  0.01512778]
   [0.8430097  0.32099164 0.02238187]
   [0.741879   0.75003886 0.00527903]
   [0.2672623  0.4121173  0.03940573]]]]
[[[[0.7671974  0.59244406 0.63892496]
   [0.6934203  0.64955604 0.5629445 ]
   [0.70462203 0.52462304 0.36873555]
   [0.7180788  0.70713127 0.56036127]
   [0.7355937  0.45318216 0.6004599 ]
   [0.88568586 0.74978274 0.18368894]
   [0.8481454  0.34582978 0.3950395 ]
   [0.848626   0.81678987 0.00693473]
   [0.9314269  0.3311935  0.00804633]
   [0.758

[[[[0.7738174  0.55361295 0.49957597]
   [0.6912358  0.6219735  0.6115261 ]
   [0.70941114 0.4978542  0.30929625]
   [0.7206112  0.7053138  0.57089764]
   [0.73388886 0.45659396 0.56290823]
   [0.8868119  0.73857516 0.21791425]
   [0.86598766 0.3606803  0.3624593 ]
   [0.8769977  0.9680667  0.01823047]
   [0.8489591  0.31269908 0.01865065]
   [0.7620832  0.73129195 0.02821472]
   [0.8352672  0.48853344 0.02797556]
   [0.7796781  0.6637764  0.01713499]
   [0.85022825 0.44699234 0.01552591]
   [1.0169675  0.75514764 0.00423199]
   [0.84646595 0.32022643 0.03620109]
   [0.8161495  0.5349479  0.00531194]
   [0.8154198  0.47681803 0.01328745]]]]
[[[[0.76726145 0.55008745 0.5675947 ]
   [0.6852573  0.619599   0.502952  ]
   [0.70911473 0.49743092 0.47425658]
   [0.71682894 0.7062358  0.5568399 ]
   [0.73280656 0.45568213 0.55076116]
   [0.88312435 0.73714036 0.19934648]
   [0.8596219  0.34530282 0.3926636 ]
   [0.8606051  0.85102355 0.00572115]
   [0.848686   0.31243172 0.02121407]
   [0.716

[[[[0.77392876 0.58256227 0.43304247]
   [0.69749975 0.6450851  0.5258697 ]
   [0.7124764  0.51884866 0.37842166]
   [0.71973574 0.7086121  0.61227256]
   [0.7350373  0.4598698  0.53343314]
   [0.88321275 0.7360008  0.24426278]
   [0.85453534 0.3575912  0.34632206]
   [0.856986   0.8548447  0.00599504]
   [0.93218243 0.34976003 0.0083594 ]
   [0.78519833 0.7326006  0.01342267]
   [0.83943814 0.49533543 0.02682784]
   [0.67572606 0.70278376 0.01588398]
   [0.6558536  0.44765973 0.0154359 ]
   [1.0190153  0.79758024 0.00543329]
   [0.84738815 0.31850442 0.03033298]
   [0.77474403 0.6830764  0.00406644]
   [0.26855764 0.41586897 0.03745514]]]]
[[[[0.7710437  0.58926123 0.44652867]
   [0.6967108  0.6504351  0.60112035]
   [0.70648396 0.521623   0.33405808]
   [0.7258382  0.71492165 0.5628673 ]
   [0.7383625  0.45844862 0.52649456]
   [0.88276875 0.7407347  0.22899479]
   [0.84985244 0.34484094 0.3956219 ]
   [0.8552784  0.83550996 0.00415775]
   [0.93019885 0.35061142 0.00707996]
   [0.753

[[[[0.7750238  0.5812611  0.41219547]
   [0.6990978  0.6457209  0.55005   ]
   [0.71519035 0.5190067  0.45373675]
   [0.7205226  0.71458256 0.6542467 ]
   [0.7395896  0.46090278 0.5608599 ]
   [0.88599986 0.7405707  0.22458741]
   [0.8596508  0.36251813 0.31709638]
   [0.8364501  0.96550155 0.01822439]
   [0.93256783 0.34977812 0.00773302]
   [0.75507677 0.7314963  0.01233289]
   [0.83845776 0.48030823 0.0223169 ]
   [0.55433494 0.648861   0.03892848]
   [0.64177394 0.44900975 0.01416659]
   [1.0188625  0.77499056 0.0054976 ]
   [0.8476948  0.3186149  0.03171089]
   [0.69867176 0.7260941  0.01081443]
   [0.26564568 0.41434354 0.04088029]]]]
[[[[0.7734114  0.59067404 0.51747596]
   [0.6984117  0.6532188  0.64272   ]
   [0.7110969  0.5238587  0.40434775]
   [0.72702956 0.7180408  0.57008064]
   [0.7438759  0.4567444  0.51359445]
   [0.8901176  0.7535163  0.18202978]
   [0.8584115  0.3582655  0.28528693]
   [0.83630514 0.9678172  0.01734623]
   [0.9322369  0.35044134 0.00682017]
   [0.717

[[[[0.7781555  0.6206009  0.53778625]
   [0.70106643 0.6690372  0.44951248]
   [0.7112249  0.5454817  0.37286523]
   [0.72794247 0.71414655 0.41108602]
   [0.7394025  0.46577114 0.6315023 ]
   [0.88898075 0.7533204  0.22309199]
   [0.85863584 0.36087084 0.36839616]
   [0.94162124 0.8345586  0.0101791 ]
   [0.93405384 0.29057503 0.01311401]
   [0.8289115  0.7315198  0.02009243]
   [0.84145397 0.48087236 0.02619362]
   [0.5122707  0.66107297 0.04694465]
   [0.66048825 0.4478231  0.01859739]
   [0.8261895  0.9563734  0.00977287]
   [0.84690917 0.31224954 0.03139105]
   [0.75964093 0.8001313  0.00404525]
   [0.26583683 0.4111522  0.05440721]]]]
[[[[0.77102244 0.6262771  0.41907963]
   [0.69841856 0.67250264 0.63444996]
   [0.709669   0.55311275 0.48207822]
   [0.7221567  0.7153394  0.54179734]
   [0.7389506  0.4663796  0.66329676]
   [0.8909546  0.75096357 0.2366679 ]
   [0.844026   0.3624022  0.4873036 ]
   [0.93993944 0.83313817 0.01037303]
   [0.93176067 0.31541473 0.01179025]
   [0.836

[[[[0.53661317 0.65111816 0.72326916]
   [0.4582387  0.69724977 0.55211097]
   [0.46524572 0.5715351  0.8280862 ]
   [0.476506   0.73738736 0.63963515]
   [0.491939   0.4829287  0.7704984 ]
   [0.7025837  0.85423815 0.8159462 ]
   [0.6054395  0.3043719  0.6466987 ]
   [0.84509706 0.9037725  0.0247426 ]
   [0.9254432  0.28287756 0.01160273]
   [0.6656528  0.783334   0.01329213]
   [0.59108686 0.5011987  0.03309262]
   [0.55303645 0.7057593  0.01206896]
   [0.31365484 0.43668675 0.03138629]
   [0.72117114 0.9522488  0.01063669]
   [0.6119122  0.27185208 0.02760816]
   [0.6516677  1.0305457  0.00296873]
   [0.7039756  0.15918796 0.0181123 ]]]]
[[[[0.52970195 0.6399205  0.7376709 ]
   [0.46290347 0.68266964 0.73782736]
   [0.4663545  0.567184   0.77690613]
   [0.48318025 0.7160613  0.6608187 ]
   [0.50016034 0.4787118  0.53647316]
   [0.7050631  0.83813417 0.8277259 ]
   [0.60981643 0.31342387 0.8392716 ]
   [0.84820676 0.8927278  0.03475171]
   [0.8550698  0.03231549 0.52591234]
   [0.662

[[[[0.29684845 0.43536013 0.6654029 ]
   [0.23157376 0.4803345  0.7698784 ]
   [0.24051438 0.38002187 0.68043476]
   [0.23938328 0.5118273  0.7444091 ]
   [0.2583366  0.30182052 0.7616806 ]
   [0.45299298 0.6102553  0.7852645 ]
   [0.46153829 0.19562787 0.843374  ]
   [0.7184434  0.7941011  0.57132804]
   [0.8519444  0.26132512 0.5589971 ]
   [0.80591834 0.85763276 0.11803854]
   [0.8401257  0.3954142  0.00772423]
   [0.859993   0.47397482 0.10168508]
   [0.84621215 0.21848719 0.14314368]
   [0.80768603 0.7840642  0.03325868]
   [0.80808514 0.02894156 0.14023966]
   [0.8424055  0.63393694 0.00726336]
   [0.7997055  0.02097508 0.07695818]]]]
[[[[0.297198   0.41428572 0.5798084 ]
   [0.23378846 0.4483816  0.77947223]
   [0.24322793 0.35385323 0.66247046]
   [0.23790058 0.48393223 0.69731337]
   [0.26430953 0.2798378  0.81819236]
   [0.4504884  0.5798446  0.8149472 ]
   [0.4736166  0.1889563  0.8018322 ]
   [0.67435    0.69974303 0.81939495]
   [0.8489384  0.23557815 0.5169845 ]
   [0.868

[[[[0.32553908 0.42956448 0.7893084 ]
   [0.2833882  0.4607999  0.67406094]
   [0.2889667  0.3845167  0.6902609 ]
   [0.30039343 0.49711388 0.7162764 ]
   [0.31450158 0.32816082 0.7433857 ]
   [0.49814802 0.56822306 0.76696616]
   [0.47238147 0.2275351  0.7898687 ]
   [0.77183294 0.67929363 0.51089925]
   [0.7757939  0.09639862 0.6333477 ]
   [0.8690537  0.7997558  0.22372958]
   [0.8292202  0.2635756  0.3413516 ]
   [0.88225263 0.49930936 0.19899237]
   [0.87898993 0.25258994 0.12624618]
   [0.8111817  0.7012939  0.13008425]
   [0.8210908  0.31438905 0.03819016]
   [0.8475894  0.45301706 0.0453338 ]
   [0.8470324  0.44932398 0.09776694]]]]
[[[[0.3178976  0.4220911  0.7407541 ]
   [0.2737269  0.45383924 0.7364617 ]
   [0.28004074 0.37587517 0.64953107]
   [0.28743666 0.4916417  0.6572093 ]
   [0.30593345 0.3201303  0.8165682 ]
   [0.49093577 0.5667701  0.7782809 ]
   [0.46582693 0.2154463  0.70721567]
   [0.7607868  0.7008257  0.722281  ]
   [0.77495086 0.08611731 0.52120274]
   [0.838

[[[[0.3297364  0.42253637 0.7576142 ]
   [0.2877679  0.4521063  0.6731636 ]
   [0.29326534 0.37902778 0.44795173]
   [0.30186024 0.49475378 0.73121125]
   [0.31842878 0.32390684 0.76122165]
   [0.47872746 0.57903147 0.8173768 ]
   [0.46187088 0.22800003 0.79904723]
   [0.7391908  0.65521795 0.5773845 ]
   [0.74531376 0.26222098 0.4751386 ]
   [0.8026689  0.6391621  0.27923912]
   [0.83615345 0.27554864 0.1880875 ]
   [0.8763517  0.51901704 0.20572475]
   [0.86051244 0.2901777  0.13724676]
   [0.8413553  0.6830373  0.07299432]
   [0.8191353  0.23980206 0.05347809]
   [0.8382012  0.57619435 0.02678093]
   [0.8368912  0.5529927  0.03344804]]]]
[[[[0.33071655 0.42268357 0.7236034 ]
   [0.28759897 0.45095903 0.69858897]
   [0.294613   0.3782718  0.50385106]
   [0.3015093  0.49179327 0.75596476]
   [0.32125401 0.32227013 0.8404336 ]
   [0.4833779  0.57797813 0.8181934 ]
   [0.46439883 0.22837397 0.82514066]
   [0.7416768  0.6569173  0.6925504 ]
   [0.7680985  0.26183826 0.5118486 ]
   [0.812

[[[[0.28795052 0.43139324 0.5536662 ]
   [0.24440221 0.46456325 0.7956842 ]
   [0.24775937 0.38792858 0.70067805]
   [0.25953975 0.5015582  0.7254437 ]
   [0.26953593 0.3206953  0.7303229 ]
   [0.43775994 0.5864669  0.6534089 ]
   [0.415207   0.22048531 0.81675047]
   [0.39755914 0.83239645 0.6714259 ]
   [0.32092428 0.06221388 0.13200921]
   [0.353181   0.97406644 0.11837542]
   [0.32357073 0.10534929 0.02439949]
   [0.87980735 0.4941482  0.31554276]
   [0.8742534  0.23827362 0.62456137]
   [0.8318354  0.7525742  0.06181934]
   [0.84803593 0.1986079  0.03136429]
   [0.9723835  0.6169958  0.00984424]
   [0.85871994 0.21468148 0.01783893]]]]
[[[[0.28903878 0.43385145 0.58872324]
   [0.24691558 0.46543747 0.7431292 ]
   [0.24954152 0.39003572 0.6613739 ]
   [0.26578388 0.5034093  0.6087882 ]
   [0.27277625 0.3240893  0.7710366 ]
   [0.43925738 0.5897258  0.71316105]
   [0.41681466 0.22663006 0.8418826 ]
   [0.400781   0.83118576 0.68865037]
   [0.32860386 0.07114897 0.10832265]
   [0.357

[[[[0.2866763  0.459509   0.7136375 ]
   [0.24265537 0.48562938 0.8403326 ]
   [0.24596024 0.4135813  0.69302875]
   [0.25628346 0.5095232  0.68036777]
   [0.27045166 0.33789146 0.7763064 ]
   [0.4425124  0.5976311  0.7692734 ]
   [0.42281502 0.22747497 0.6795238 ]
   [0.43233347 0.8509571  0.6164807 ]
   [0.39691132 0.01539537 0.15423909]
   [0.41293013 0.9738526  0.1863718 ]
   [0.37384707 0.08282121 0.04831558]
   [0.8890469  0.49833465 0.16494966]
   [0.8795771  0.2368568  0.38217926]
   [0.8496126  0.7594166  0.03666234]
   [0.77314776 0.2569976  0.00762507]
   [0.8393895  0.8013854  0.00597429]
   [1.014344   0.17658238 0.01529381]]]]
[[[[0.27906772 0.44486532 0.8359053 ]
   [0.23966442 0.4730379  0.85775286]
   [0.2410296  0.4011911  0.79035956]
   [0.25436082 0.50602233 0.7558949 ]
   [0.26298934 0.33258536 0.62449074]
   [0.43387672 0.5975593  0.7572924 ]
   [0.41707775 0.22480023 0.8048587 ]
   [0.4249497  0.854464   0.5917011 ]
   [0.38543397 0.05746686 0.20720506]
   [0.404

[[[[0.2568042  0.39667958 0.63011193]
   [0.21297607 0.431948   0.8372222 ]
   [0.21048898 0.35411805 0.57048994]
   [0.23834243 0.46896982 0.7639936 ]
   [0.2385216  0.29262185 0.6117557 ]
   [0.41881305 0.54459745 0.8849722 ]
   [0.39327955 0.2090581  0.84559685]
   [0.5436026  0.77177596 0.8250277 ]
   [0.53559536 0.02448721 0.2399536 ]
   [0.3262039  0.59729725 0.6065741 ]
   [0.2993492  0.17454392 0.6262447 ]
   [0.8604953  0.4825546  0.13615641]
   [0.8570775  0.2199974  0.22587249]
   [0.8426623  0.7632942  0.10393691]
   [0.8606709  0.17246583 0.02338436]
   [0.8381157  0.65020084 0.01222247]
   [0.839448   0.32392216 0.00324786]]]]
[[[[0.2590575  0.39929757 0.7346887 ]
   [0.21591114 0.43527827 0.83201206]
   [0.21487175 0.35537574 0.665154  ]
   [0.2424022  0.47611222 0.74073714]
   [0.2472704  0.29524    0.63312805]
   [0.4301023  0.5399313  0.89200807]
   [0.40399563 0.2098794  0.7725043 ]
   [0.59665656 0.74208164 0.67997843]
   [0.6034194  0.02690937 0.4700439 ]
   [0.350

[[[[0.33050698 0.57372975 0.76183057]
   [0.2573572  0.612088   0.7949599 ]
   [0.2681198  0.5057971  0.65778345]
   [0.2626872  0.65158445 0.5463993 ]
   [0.2959162  0.4177884  0.7351819 ]
   [0.47289488 0.7597252  0.8381481 ]
   [0.48691642 0.33009267 0.6880766 ]
   [0.7905041  0.89668673 0.82253516]
   [0.6953006  0.13703659 0.39118308]
   [0.83397114 0.926574   0.02242064]
   [0.7809996  0.03367417 0.25701874]
   [0.88138044 0.69739646 0.13540229]
   [0.89935935 0.43585235 0.08532399]
   [0.8527006  0.87746894 0.01203594]
   [0.82850116 0.3819561  0.01203993]
   [0.9993395  0.9606497  0.01759359]
   [0.848283   0.02056982 0.03330055]]]]
[[[[0.3138362  0.58258796 0.5364229 ]
   [0.24494082 0.6242729  0.47616622]
   [0.25090924 0.5171541  0.5458784 ]
   [0.25129962 0.66516155 0.5612438 ]
   [0.27464914 0.42529747 0.7230575 ]
   [0.4731408  0.7790413  0.908652  ]
   [0.45653278 0.34693784 0.6129877 ]
   [0.82724595 0.8756153  0.761269  ]
   [0.66017365 0.08929159 0.37803423]
   [0.871

[[[[ 0.32629833  0.21169047  0.03000781]
   [ 0.1065058   0.50038785  0.00438219]
   [ 0.08912667  0.4082967   0.00390807]
   [-0.00097453  0.67905426  0.0143961 ]
   [ 0.06932326  0.75327396  0.0391739 ]
   [ 0.14918634  0.6245301   0.01206732]
   [ 0.1779204   0.33715495  0.01421192]
   [ 0.38559374  0.67736405  0.01790604]
   [ 0.41622707  0.29902875  0.05961505]
   [ 0.57608765  0.6572352   0.01434353]
   [ 0.6084752   0.37655503  0.02775413]
   [ 0.5757227   0.5772962   0.04139778]
   [ 0.5734506   0.3768139   0.03901696]
   [ 0.81561506  0.5234802   0.02309644]
   [ 0.8188932   0.37762865  0.02959138]
   [ 0.9049686   0.50303763  0.01007903]
   [ 0.8494861   0.387058    0.02588344]]]]
[[[[0.40633023 0.6453886  0.69593364]
   [0.33833846 0.6865034  0.704872  ]
   [0.3398028  0.5714428  0.7051738 ]
   [0.3667496  0.7288121  0.4424388 ]
   [0.38250166 0.4753927  0.5679882 ]
   [0.58734363 0.8157613  0.84345096]
   [0.5380891  0.388694   0.6853989 ]
   [0.8572301  0.86825657 0.487907

[[[[0.42122996 0.55390286 0.72698706]
   [0.38610408 0.5782361  0.82232034]
   [0.38821742 0.511424   0.7589705 ]
   [0.41102406 0.60523367 0.62725025]
   [0.42346677 0.4533747  0.7954763 ]
   [0.605782   0.7287893  0.8530376 ]
   [0.61912113 0.36949557 0.8678389 ]
   [0.85262245 0.83215296 0.68339425]
   [0.86968124 0.308724   0.3405438 ]
   [0.87300026 0.86781424 0.03457376]
   [0.8695296  0.33276802 0.01199493]
   [0.94713676 0.6714754  0.06597763]
   [0.9713678  0.46138817 0.03585291]
   [0.85849524 0.82364815 0.02235603]
   [0.6387114  0.38315427 0.06234697]
   [0.86571455 0.88469887 0.00506121]
   [0.8439545  0.5680315  0.00129104]]]]
[[[[0.4249577  0.55190635 0.7868029 ]
   [0.38885295 0.57481134 0.86848235]
   [0.39331496 0.5079063  0.63759   ]
   [0.40895256 0.5961518  0.72914594]
   [0.42996997 0.44862947 0.8498144 ]
   [0.6041651  0.72260857 0.868343  ]
   [0.61878186 0.36859375 0.86334795]
   [0.855374   0.82609403 0.7292878 ]
   [0.8588022  0.299341   0.4955139 ]
   [0.873

[[[[0.4288252  0.555058   0.74778163]
   [0.38470095 0.57757777 0.8071871 ]
   [0.3925953  0.5082854  0.70191747]
   [0.39954025 0.5977634  0.63592446]
   [0.42430958 0.44622135 0.8076501 ]
   [0.5959075  0.7281534  0.889251  ]
   [0.6131798  0.36313233 0.79456437]
   [0.8643633  0.8261973  0.55592227]
   [0.8747456  0.28755188 0.2810645 ]
   [0.87476015 0.8645487  0.03288743]
   [0.8878006  0.28799963 0.01047018]
   [0.9487926  0.6796309  0.05756852]
   [0.97645205 0.45866153 0.03227916]
   [0.87123954 0.8193721  0.01631951]
   [0.6249753  0.36959502 0.06610247]
   [1.0044465  0.96279347 0.0173347 ]
   [0.864298   0.6076377  0.00147769]]]]
[[[[0.42867348 0.55482674 0.7589908 ]
   [0.38416755 0.57775354 0.79393584]
   [0.3917355  0.50736463 0.7226211 ]
   [0.39928195 0.59916544 0.63535845]
   [0.42217845 0.44631338 0.80422676]
   [0.5932605  0.7266835  0.8965579 ]
   [0.6099303  0.36480138 0.7485932 ]
   [0.85735166 0.8237598  0.67234427]
   [0.86655676 0.28796047 0.5954668 ]
   [0.874

[[[[0.44453734 0.54712397 0.7038059 ]
   [0.40213987 0.5722153  0.63969654]
   [0.41333672 0.5025505  0.59732425]
   [0.4073728  0.60486025 0.49936488]
   [0.43138117 0.44490406 0.80177397]
   [0.56133956 0.70734113 0.6978054 ]
   [0.584952   0.37990984 0.6735515 ]
   [0.72393036 0.70589685 0.41116256]
   [0.73108405 0.4060198  0.40292898]
   [0.7156601  0.70424557 0.10030928]
   [0.73435473 0.4127925  0.15646201]
   [0.9028265  0.6583675  0.09718704]
   [0.91071177 0.5117645  0.04732031]
   [0.7340519  0.70530534 0.17584413]
   [0.749681   0.43968648 0.10488215]
   [0.8217857  0.77201045 0.00972131]
   [0.80867743 0.57815164 0.00845397]]]]
[[[[0.44253084 0.55115306 0.689917  ]
   [0.4008513  0.5752381  0.6231637 ]
   [0.41126785 0.50605774 0.60007   ]
   [0.40989387 0.6069898  0.5647437 ]
   [0.43269297 0.447021   0.81129944]
   [0.5645081  0.7059058  0.73673177]
   [0.58626807 0.38169378 0.7204538 ]
   [0.7296649  0.7071512  0.40455988]
   [0.73319113 0.40420756 0.46806952]
   [0.730

[[[[0.44644535 0.54039085 0.5515645 ]
   [0.4004901  0.56579673 0.50572795]
   [0.4131183  0.49342415 0.6363097 ]
   [0.40217453 0.59115595 0.6675479 ]
   [0.43176413 0.42637944 0.77893317]
   [0.51894695 0.6952319  0.8330964 ]
   [0.5544274  0.37062657 0.73703265]
   [0.8123538  0.75135887 0.36937636]
   [0.8023099  0.386929   0.5717719 ]
   [0.8249408  0.73163116 0.04055962]
   [0.82764506 0.40111595 0.03949407]
   [0.9095526  0.68504286 0.04318979]
   [0.90899646 0.44573122 0.04140767]
   [0.8408818  0.74372554 0.02027801]
   [0.8455578  0.3739422  0.05064502]
   [0.9726554  0.882601   0.00838923]
   [0.8589581  0.61168224 0.00110069]]]]
[[[[0.44871306 0.53843415 0.6105356 ]
   [0.40049252 0.5651057  0.51415354]
   [0.41380736 0.491302   0.6520722 ]
   [0.39949846 0.59129864 0.62345284]
   [0.43065283 0.42294806 0.7793899 ]
   [0.51041245 0.692469   0.6695798 ]
   [0.5487212  0.37007734 0.8889362 ]
   [0.80428016 0.74687994 0.38327336]
   [0.802109   0.39401406 0.6177682 ]
   [0.799

[[[[0.43091294 0.5560719  0.64422   ]
   [0.3903001  0.5807265  0.74897486]
   [0.3967614  0.51619214 0.590878  ]
   [0.4043306  0.60056126 0.59492135]
   [0.41843218 0.45192897 0.5782591 ]
   [0.56238425 0.665006   0.800215  ]
   [0.56508607 0.3984458  0.599992  ]
   [0.5729627  0.8367786  0.77027345]
   [0.62215936 0.32428092 0.40324706]
   [0.45254087 0.7288426  0.7811695 ]
   [0.46938837 0.36709687 0.5245931 ]
   [0.9090008  0.6830484  0.04309776]
   [0.9069532  0.45214134 0.02112556]
   [0.84103703 0.85654896 0.02014065]
   [0.80487657 0.4031409  0.01471555]
   [0.81067    0.8996021  0.00736603]
   [0.46624887 0.37552366 0.03791776]]]]
[[[[0.43265396 0.5569148  0.62889045]
   [0.39309117 0.58122087 0.7171091 ]
   [0.39905137 0.51644677 0.6490918 ]
   [0.40678856 0.5979204  0.6207785 ]
   [0.42100352 0.45015436 0.65100694]
   [0.56138694 0.6614854  0.65294343]
   [0.56446826 0.40053126 0.5214226 ]
   [0.55427    0.8075584  0.74986553]
   [0.6045166  0.3759776  0.39703622]
   [0.456

[[[[0.4294147  0.56680024 0.7417159 ]
   [0.39111584 0.5935006  0.79744047]
   [0.39661765 0.52357984 0.45456702]
   [0.40276462 0.6170111  0.67455375]
   [0.41744393 0.4631506  0.64779013]
   [0.55907357 0.7158243  0.76764166]
   [0.5701747  0.38620648 0.88996613]
   [0.59667146 0.9657535  0.79854524]
   [0.6090553  0.16687743 0.8116133 ]
   [0.47633857 0.74731743 0.73879313]
   [0.4768806  0.37080646 0.7773596 ]
   [0.94666713 0.695492   0.01242229]
   [0.9282856  0.43872723 0.00873157]
   [0.7513399  0.95995533 0.02516827]
   [0.7518815  0.4373129  0.00228396]
   [0.8603445  0.965948   0.00759593]
   [0.47588667 0.3807646  0.06931967]]]]
[[[[0.43198273 0.56669366 0.71577084]
   [0.3931031  0.59504664 0.7975724 ]
   [0.39673972 0.5236238  0.4703722 ]
   [0.40583166 0.6242262  0.5044222 ]
   [0.41257378 0.46337783 0.7081429 ]
   [0.5568978  0.7179612  0.76798356]
   [0.5669007  0.38815913 0.6242003 ]
   [0.61165667 0.9677973  0.64077675]
   [0.6242917  0.1634364  0.7346656 ]
   [0.474

[[[[0.4343884  0.56574345 0.7027856 ]
   [0.39240107 0.59448504 0.7776406 ]
   [0.39444584 0.5230168  0.4560841 ]
   [0.40353572 0.6180314  0.7464352 ]
   [0.41834897 0.46085668 0.62432045]
   [0.56536347 0.7144577  0.89902365]
   [0.58675003 0.38220888 0.791672  ]
   [0.720057   0.95852757 0.6794041 ]
   [0.77083564 0.2001377  0.75836504]
   [0.49075413 0.7724227  0.59722877]
   [0.5022991  0.32970446 0.59214926]
   [0.9536054  0.68386596 0.01522103]
   [0.94722366 0.4638203  0.00629064]
   [0.81099313 0.87204874 0.01060897]
   [0.81573176 0.4089095  0.00426447]
   [0.9377043  0.92420024 0.00492114]
   [0.4970497  0.33413658 0.02374274]]]]
[[[[0.43416816 0.5642192  0.6710783 ]
   [0.39114624 0.5933269  0.7983876 ]
   [0.3977111  0.5213387  0.4324686 ]
   [0.4016286  0.6186898  0.739097  ]
   [0.41741693 0.46465835 0.6547896 ]
   [0.57338035 0.7151387  0.63017863]
   [0.58457804 0.3838013  0.7932235 ]
   [0.73809123 0.9531505  0.6358472 ]
   [0.78605074 0.20313285 0.76419353]
   [0.501

[[[[0.4162726  0.5622468  0.47697026]
   [0.37694526 0.5868162  0.5857052 ]
   [0.3837169  0.518023   0.6798117 ]
   [0.39168847 0.61106575 0.605184  ]
   [0.4121396  0.46251774 0.6841848 ]
   [0.5816386  0.7148596  0.7619785 ]
   [0.58471996 0.37694007 0.91160357]
   [0.8050696  0.8919879  0.8279865 ]
   [0.8467435  0.24693339 0.7866856 ]
   [0.7174303  0.9783644  0.11866385]
   [0.7041008  0.20161858 0.7352865 ]
   [0.97405696 0.6740793  0.04827842]
   [0.977795   0.46898597 0.02110642]
   [0.8240255  0.9005558  0.01958382]
   [0.85855925 0.26154682 0.04081297]
   [0.7164962  0.9903342  0.01856288]
   [0.7099306  0.18498817 0.03057531]]]]
[[[[0.41402936 0.53827274 0.64219487]
   [0.37158    0.56537837 0.5941863 ]
   [0.38678604 0.49394816 0.7428689 ]
   [0.38580596 0.604486   0.6398345 ]
   [0.42246604 0.4492036  0.8608999 ]
   [0.5794071  0.71805024 0.7533798 ]
   [0.58570015 0.37504482 0.7628516 ]
   [0.80178666 0.89174765 0.7526838 ]
   [0.8565376  0.24848887 0.73387593]
   [0.719

[[[[0.40842718 0.5252222  0.7437693 ]
   [0.37019438 0.5531282  0.7798642 ]
   [0.37600493 0.48082456 0.417197  ]
   [0.3899539  0.5857682  0.67962444]
   [0.40906823 0.4242258  0.78974235]
   [0.57421726 0.6999182  0.7238058 ]
   [0.6037257  0.34704238 0.9307236 ]
   [0.84603786 0.82653475 0.7556493 ]
   [0.8528194  0.26367497 0.57218516]
   [0.86795914 0.8610708  0.04501322]
   [0.8848345  0.2448444  0.02601582]
   [0.92811465 0.6623369  0.06672823]
   [0.959646   0.4371127  0.03128472]
   [0.84926724 0.8303846  0.03877577]
   [0.6162442  0.35141084 0.07382053]
   [0.8719291  0.8647241  0.005483  ]
   [0.85942066 0.02009601 0.02765399]]]]
[[[[0.43227908 0.53371125 0.7736534 ]
   [0.3872971  0.56236506 0.73546994]
   [0.39451417 0.48794287 0.64900315]
   [0.39944357 0.5901169  0.706907  ]
   [0.4184152  0.42792794 0.73297375]
   [0.5807197  0.70061415 0.8222016 ]
   [0.60862297 0.3459761  0.9492159 ]
   [0.8476653  0.8296658  0.835488  ]
   [0.86064625 0.27156794 0.61428165]
   [0.871

[[[[0.49288183 0.48581216 0.7055216 ]
   [0.44161588 0.5228397  0.6001258 ]
   [0.4555742  0.44549996 0.76715034]
   [0.4448266  0.59077156 0.81562436]
   [0.4705759  0.41764885 0.6502399 ]
   [0.6061757  0.7120831  0.9127259 ]
   [0.6618457  0.33634478 0.8603623 ]
   [0.8838074  0.79184747 0.173565  ]
   [0.8754146  0.29601038 0.05663222]
   [0.68034834 0.5783794  0.48604083]
   [0.6808163  0.51326364 0.04207358]
   [0.94902205 0.7220999  0.00973567]
   [0.8953811  0.97401345 0.01364738]
   [0.61299974 0.7268779  0.02236703]
   [0.64844155 0.33995602 0.02197045]
   [0.6880207  0.9820578  0.01882643]
   [0.97568667 0.00290395 0.012247  ]]]]
[[[[0.48883092 0.48171073 0.620755  ]
   [0.44196722 0.5185906  0.7092656 ]
   [0.45525062 0.44108623 0.7362649 ]
   [0.4512279  0.5852422  0.6299139 ]
   [0.47809637 0.4148849  0.5524747 ]
   [0.6148612  0.71282786 0.9174652 ]
   [0.6699149  0.33184975 0.75616074]
   [0.8825315  0.8141648  0.31258443]
   [0.872568   0.2984655  0.06441623]
   [0.704

[[[[0.50336486 0.5090915  0.64681417]
   [0.47249776 0.54102004 0.58435535]
   [0.47000563 0.4752671  0.7256499 ]
   [0.49640176 0.5815257  0.67432696]
   [0.4953534  0.4268834  0.6686902 ]
   [0.6173073  0.6551925  0.80107224]
   [0.6959224  0.33910823 0.67488414]
   [0.48169598 0.8474907  0.778435  ]
   [0.4091329  0.41792417 0.03722778]
   [0.35072777 0.6326895  0.5153314 ]
   [0.43045962 0.4523701  0.03075135]
   [0.94877577 0.6642638  0.02514499]
   [0.9822297  0.40907583 0.00628209]
   [0.48836005 0.84326744 0.06111792]
   [0.6864431  0.33467183 0.02660882]
   [0.3527506  0.6328839  0.02246338]
   [0.18838316 0.7414076  0.0211488 ]]]]
[[[[0.4973653  0.5049293  0.65731424]
   [0.4639319  0.53520286 0.74709636]
   [0.46697384 0.4668882  0.79010385]
   [0.48722714 0.5736965  0.72525275]
   [0.49568516 0.42066276 0.64862484]
   [0.6207245  0.6704068  0.63633096]
   [0.69640964 0.33760178 0.68996143]
   [0.5969956  0.9162974  0.72815824]
   [0.8678126  0.30258402 0.02281561]
   [0.391

[[[[0.48853242 0.52336866 0.67513514]
   [0.44146535 0.55333805 0.79122907]
   [0.45519838 0.4766931  0.5875627 ]
   [0.45058554 0.5893414  0.71152765]
   [0.47896832 0.42550403 0.75347596]
   [0.6273603  0.7159982  0.88179934]
   [0.6693799  0.34068584 0.8467929 ]
   [0.8606863  0.8390598  0.64902425]
   [0.87687707 0.306806   0.07692122]
   [0.8724965  0.88336813 0.03819075]
   [0.8572968  0.37098294 0.00807792]
   [0.97488797 0.6726619  0.03997639]
   [0.98774385 0.42364472 0.0088529 ]
   [0.86772126 0.8425993  0.0266327 ]
   [0.6734845  0.3468977  0.03620741]
   [0.9988769  0.96663094 0.02379432]
   [0.8220856  0.51034164 0.00201491]]]]
[[[[0.48830494 0.49763712 0.5293624 ]
   [0.4416837  0.53184575 0.7941309 ]
   [0.45889148 0.45561752 0.5896622 ]
   [0.4531152  0.5847838  0.69074357]
   [0.48657674 0.41907305 0.7621884 ]
   [0.6270492  0.71208906 0.8847214 ]
   [0.65547866 0.3389902  0.92435193]
   [0.8653898  0.8433108  0.52680147]
   [0.8965189  0.29412866 0.10605469]
   [0.872

[[[[0.50052226 0.4758005  0.5199432 ]
   [0.45019802 0.4962077  0.4343142 ]
   [0.4881396  0.43820894 0.40524006]
   [0.43882066 0.53798354 0.46089032]
   [0.5132517  0.40117925 0.67364836]
   [0.6168692  0.7250774  0.89861035]
   [0.6681094  0.350597   0.8861325 ]
   [0.85615414 0.84122205 0.15766639]
   [0.85838175 0.45012528 0.26971406]
   [0.62190247 0.6037967  0.06517726]
   [0.6227757  0.49775022 0.51632047]
   [0.9116582  0.705265   0.01713392]
   [0.9106278  0.44702405 0.03753483]
   [0.8672299  0.84371775 0.00659928]
   [0.65228236 0.35897645 0.19883022]
   [1.0131831  0.96582305 0.01400578]
   [0.59176934 0.5064419  0.05109146]]]]
[[[[0.4967609  0.49612182 0.4171445 ]
   [0.43786165 0.50019664 0.37425485]
   [0.4664821  0.45710012 0.40793508]
   [0.43396896 0.5419941  0.4101013 ]
   [0.51421946 0.39762878 0.52291447]
   [0.61502534 0.72109973 0.69681764]
   [0.67400086 0.34398314 0.66065043]
   [0.8492296  0.8379551  0.37370744]
   [0.8579974  0.45644712 0.46873617]
   [0.544

[[[[0.4747642  0.54833114 0.685056  ]
   [0.42041633 0.58082694 0.70241004]
   [0.4281263  0.4908058  0.72298825]
   [0.43764758 0.60793835 0.5835139 ]
   [0.4608762  0.4208024  0.6457039 ]
   [0.6255888  0.7448242  0.7991694 ]
   [0.64864993 0.33526775 0.842453  ]
   [0.8702581  0.8603372  0.07660577]
   [0.8794242  0.23913112 0.04448673]
   [0.46305698 0.78314114 0.0234125 ]
   [0.13987213 0.757367   0.03224644]
   [0.9904312  0.6815104  0.01449087]
   [0.9822514  0.41272888 0.01203299]
   [0.6472705  0.7762867  0.00914401]
   [0.6315923  0.33892304 0.03184426]
   [0.70522404 0.98904556 0.00804779]
   [0.8625145  0.00724476 0.01732031]]]]
[[[[0.4686306  0.55072546 0.7892184 ]
   [0.411404   0.58275235 0.5350343 ]
   [0.42209885 0.4905669  0.6651336 ]
   [0.4273213  0.613708   0.7023027 ]
   [0.4540926  0.41968244 0.66497755]
   [0.637888   0.75869864 0.84254354]
   [0.6487851  0.33384725 0.8495296 ]
   [0.8600878  0.85646045 0.14217761]
   [0.88927925 0.24016999 0.03718105]
   [0.456

[[[[0.41345713 0.52619606 0.71543956]
   [0.37002572 0.56020546 0.6699854 ]
   [0.37951344 0.47572434 0.5568164 ]
   [0.40135428 0.6067953  0.6201091 ]
   [0.42966232 0.42164844 0.78738457]
   [0.6275528  0.7620009  0.89132524]
   [0.63304484 0.31594735 0.76272595]
   [0.87750787 0.90437484 0.14498037]
   [0.845883   0.20907055 0.25486442]
   [0.8812205  0.9275125  0.02201673]
   [0.87774295 0.14941761 0.07273453]
   [0.9747001  0.66334224 0.02439952]
   [0.9771278  0.43678257 0.01623169]
   [0.64176834 0.7957706  0.02535102]
   [0.6911974  0.43430254 0.02110794]
   [0.7079375  0.99437463 0.00867766]
   [0.87959707 0.14266752 0.01336938]]]]
[[[[0.43946648 0.5173807  0.48156315]
   [0.3939829  0.5501497  0.75329185]
   [0.40629587 0.4679138  0.83256835]
   [0.41619313 0.5982789  0.6665503 ]
   [0.44883057 0.41814274 0.75298995]
   [0.6330689  0.76206434 0.8803512 ]
   [0.64606464 0.3255046  0.9190339 ]
   [0.86903375 0.93797386 0.31265062]
   [0.8414309  0.12985909 0.53733104]
   [0.881

[[[[0.3548839  0.37625012 0.5145066 ]
   [0.30525154 0.43480572 0.59483665]
   [0.32116753 0.32321644 0.5302146 ]
   [0.32049513 0.5038042  0.35298204]
   [0.33889136 0.27764004 0.5503711 ]
   [0.5002966  0.6980579  0.2064794 ]
   [0.554566   0.18633793 0.49105573]
   [0.5551126  0.8311372  0.15909058]
   [0.608284   0.12478175 0.0431594 ]
   [0.53305185 0.82211393 0.10382736]
   [0.5900003  0.12427512 0.32733232]
   [0.64554226 0.8078133  0.09447682]
   [0.73238814 0.7864791  0.06875411]
   [0.59052855 0.8282068  0.09006846]
   [0.6284535  0.27863872 0.00521144]
   [0.53917634 0.840044   0.05080682]
   [0.41671535 0.31103215 0.02524853]]]]
[[[[0.38509402 0.43234146 0.7501354 ]
   [0.33651716 0.47208363 0.826977  ]
   [0.3384828  0.3791432  0.7040353 ]
   [0.35319003 0.5104888  0.7549605 ]
   [0.3692648  0.31032884 0.6084147 ]
   [0.50792885 0.6175548  0.7868297 ]
   [0.55435    0.1750553  0.43477368]
   [0.6335818  0.9295299  0.6751067 ]
   [0.8400831  0.02384715 0.21195307]
   [0.678

[[[[0.3959307  0.51359004 0.5550713 ]
   [0.33742768 0.55411285 0.7336381 ]
   [0.3428859  0.45885262 0.6534974 ]
   [0.34476417 0.5909482  0.7637327 ]
   [0.35869536 0.38535517 0.7807993 ]
   [0.51107264 0.70440024 0.7325335 ]
   [0.52556694 0.2885186  0.91688967]
   [0.80255264 0.82907236 0.66370755]
   [0.79926085 0.18860918 0.40191293]
   [0.8635069  0.7484957  0.20673892]
   [0.8452141  0.23132251 0.13551605]
   [0.9216744  0.6201523  0.05653009]
   [0.918903   0.34848914 0.06100592]
   [0.81930304 0.80570924 0.03732586]
   [0.82266235 0.34376007 0.08068696]
   [0.84945095 0.6771083  0.01357633]
   [0.8402493  0.5755539  0.01223654]]]]
[[[[0.41252598 0.5101478  0.7465358 ]
   [0.35969576 0.5461659  0.6734688 ]
   [0.36865705 0.46092412 0.7278697 ]
   [0.36574864 0.5808493  0.70982873]
   [0.38233265 0.39338267 0.6007613 ]
   [0.5245562  0.6918355  0.90824515]
   [0.53563404 0.29988754 0.69477475]
   [0.78168297 0.7995872  0.62002975]
   [0.79085696 0.20650563 0.5293566 ]
   [0.853

[[[[0.43383345 0.5028766  0.63480127]
   [0.3860826  0.5383954  0.78522635]
   [0.39408344 0.4568922  0.5696655 ]
   [0.40060526 0.58097184 0.40725613]
   [0.41781348 0.401236   0.6925578 ]
   [0.55242926 0.68359935 0.70826983]
   [0.56013066 0.3192303  0.79613507]
   [0.80160165 0.75193083 0.40421355]
   [0.8187697  0.26273558 0.41759944]
   [0.84261954 0.6535126  0.18929246]
   [0.81742877 0.44165003 0.09429857]
   [0.9167709  0.61332107 0.04987949]
   [0.9287424  0.39034125 0.04185781]
   [0.7725069  0.75492954 0.09400174]
   [0.817765   0.36189562 0.1294257 ]
   [0.84731007 0.65746367 0.01917794]
   [0.8332453  0.46968848 0.0409728 ]]]]
[[[[0.43143877 0.5052159  0.720288  ]
   [0.38436338 0.5408141  0.7355554 ]
   [0.39241612 0.45867452 0.6303836 ]
   [0.3984129  0.58194196 0.4104755 ]
   [0.41545427 0.403206   0.76408815]
   [0.5466579  0.6840305  0.87878984]
   [0.5560018  0.32463515 0.7347696 ]
   [0.78933114 0.7523382  0.44794697]
   [0.8104695  0.2636547  0.3950959 ]
   [0.838

[[[[0.56765544 0.62483823 0.5639205 ]
   [0.50887877 0.6611754  0.8061088 ]
   [0.5095347  0.5624101  0.6612308 ]
   [0.5288627  0.68609214 0.5320589 ]
   [0.54273987 0.4723078  0.6210396 ]
   [0.73519564 0.79542315 0.7831067 ]
   [0.7353859  0.3377758  0.7471981 ]
   [0.8775996  0.9684912  0.03139859]
   [0.8553479  0.2592112  0.06073251]
   [0.74751365 0.7372884  0.01416692]
   [0.86370456 0.14922418 0.04115298]
   [0.49152303 0.8068132  0.01415116]
   [0.3492192  0.7639105  0.02291411]
   [0.78310144 0.9713634  0.01434445]
   [0.78620684 0.42161644 0.00740278]
   [0.7805879  1.0169593  0.00650522]
   [0.8427393  0.02009137 0.01948157]]]]
[[[[0.5533898  0.62268376 0.6292069 ]
   [0.4980747  0.6609827  0.64929146]
   [0.49905056 0.5603409  0.528004  ]
   [0.5141988  0.6839668  0.7191284 ]
   [0.52930176 0.46979356 0.8027656 ]
   [0.72365844 0.7991146  0.8375417 ]
   [0.7186998  0.3380539  0.7798449 ]
   [0.8637811  0.86520433 0.01044327]
   [0.8437681  0.2776584  0.13219318]
   [0.742

[[[[5.11437297e-01 5.52994668e-01 7.50657201e-01]
   [4.35117245e-01 5.95632076e-01 6.00033998e-01]
   [4.46980238e-01 4.78646725e-01 6.28975511e-01]
   [4.34456408e-01 6.37818098e-01 6.70864284e-01]
   [4.65654731e-01 3.96143645e-01 4.84407216e-01]
   [6.46915913e-01 7.75669992e-01 7.97101080e-01]
   [6.62132144e-01 2.78476059e-01 6.94539249e-01]
   [8.80032003e-01 9.20700252e-01 2.72051394e-02]
   [8.91537845e-01 1.46769583e-01 3.12073827e-02]
   [8.02766502e-01 9.75377798e-01 3.07398438e-02]
   [9.22016263e-01 4.15839314e-01 1.78539753e-03]
   [5.15430987e-01 6.07785344e-01 4.95657325e-03]
   [3.68540823e-01 3.30696404e-01 6.52623177e-03]
   [6.56469345e-01 7.94977069e-01 1.34521425e-02]
   [6.75795913e-01 2.74834007e-01 3.83842289e-02]
   [6.82180047e-01 1.01634908e+00 6.20636344e-03]
   [6.89419150e-01 5.16561568e-01 6.66916370e-04]]]]
[[[[5.1197338e-01 5.5373776e-01 7.1111941e-01]
   [4.3558729e-01 5.9714425e-01 5.7706481e-01]
   [4.4600210e-01 4.8162836e-01 6.7155808e-01]
   [4.

**How to get data**

In [13]:
right_eye = keypoints_with_scores[0][0][2]
np.array(right_eye[:-1]*[480,640]).astype(int)

array([209, 335])

In [15]:
shaped = np.squeeze(interpreter.get_tensor(output_details[0]['index'])*[480,640,1])
#print(shaped)
for kp in shaped:
    ky,kx,kp_conf = kp
    print(int(kx),int(ky),kp_conf)

379 236 0.7692314386367798
405 204 0.7363525629043579
335 209 0.47225403785705566
432 214 0.6654006242752075
289 228 0.7968537211418152
531 310 0.7863597869873047
215 331 0.8477886915206909
595 420 0.03343367576599121
190 422 0.03146308660507202
460 300 0.00731930136680603
292 383 0.0031796395778656006
259 208 0.009642869234085083
268 163 0.008072346448898315
618 315 0.01788806915283203
214 326 0.01835101842880249
651 245 0.009585678577423096
650 235 0.006071269512176514


## Draw Keypoints

In [16]:
def draw_keypoints(frame,keypoints,confidence):
    y,x,c = frame.shape
    shaped = np.squeeze(keypoints*[y,x,1])
    
    for kp in shaped:
        ky,kx,kp_conf = kp
        if kp_conf>confidence:
            cv2.circle(frame,(int(kx),int(ky)),4,(0,255,0),-1)
            

## Draw Edges

In [22]:
EDGES = {
    (0, 1): 'm',
    (0, 2): 'c',
    (1, 3): 'm',
    (2, 4): 'c',
    (0, 5): 'm',
    (0, 6): 'c',
    (5, 7): 'm',
    (7, 9): 'm',
    (6, 8): 'c',
    (8, 10): 'c',
    (5, 6): 'y',
    (5, 11): 'm',
    (6, 12): 'c',
    (11, 12): 'y',
    (11, 13): 'm',
    (13, 15): 'm',
    (12, 14): 'c',
    (14, 16): 'c'
}
#All connections

In [25]:
def draw_connections(frame,keypoints,edges,confidence):
    y,x,c = frame.shape
    shaped = np.squeeze(keypoints*[y,x,1]) 
    for edge,color in edges.items():
        p1,p2 = edge
        y1,x1,c1 = shaped[p1]
        y2,x2,c2 = shaped[p2]
        
        if(c1>confidence and c2>confidence):
            cv2.line(frame,(int(x1),int(y1)),(int(x2),int(y2)),(255,0,0),2)